import type { NextPage } from 'next';
import Head from 'next/head';

import { Grid, Box, Typography, Container } from '@mui/material';
import Post from '../components/Post/Post';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Посты</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container component="main">
        <Box
          sx={{
            paddingTop: 4,
          }}>
          <Typography
            sx={{
              color: '#fff',
              fontWeight: 500,
            }}
            component="h1"
            variant="h2">
            Latest
          </Typography>
          <Box component="form" noValidate sx={{ mt: 3 }}>
            <Grid container spacing={2}>
              <Grid item xs={12}>
                <Post />
              </Grid>
            </Grid>
          </Box>
        </Box>
      </Container>
    </>
  );
};

export default Home;
